byte qmaq[] = {
M_qmaq_000, M_qmaq_001, M_qmaq_002, M_qmaq_003, M_qmaq_004, M_qmaq_005, M_qmaq_006, M_qmaq_007, 
M_qmaq_008, M_qmaq_009, M_qmaq_00A, M_qmaq_00B, M_qmaq_00C, M_qmaq_00D, M_qmaq_00E, M_qmaq_00F, 
M_qmaq_010, M_qmaq_011, M_qmaq_012, M_qmaq_013, M_qmaq_014, M_qmaq_015, M_qmaq_016, M_qmaq_017, 
M_qmaq_018, M_qmaq_019, M_qmaq_01A, M_qmaq_01B, M_qmaq_01C, M_qmaq_01D, M_qmaq_01E, M_qmaq_01F, 
M_qmaq_020, M_qmaq_021, M_qmaq_022, M_qmaq_023, M_qmaq_024, M_qmaq_025, M_qmaq_026, M_qmaq_027, 
M_qmaq_028, M_qmaq_029, M_qmaq_02A, M_qmaq_02B, M_qmaq_02C, M_qmaq_02D, M_qmaq_02E, M_qmaq_02F, 
M_qmaq_030, M_qmaq_031, M_qmaq_032, M_qmaq_033, M_qmaq_034, M_qmaq_035, M_qmaq_036, M_qmaq_037, 
M_qmaq_038, M_qmaq_039, M_qmaq_03A, M_qmaq_03B, M_qmaq_03C, M_qmaq_03D, M_qmaq_03E, M_qmaq_03F, 
M_qmaq_040, M_qmaq_041, M_qmaq_042, M_qmaq_043, M_qmaq_044, M_qmaq_045, M_qmaq_046, M_qmaq_047, 
M_qmaq_048, M_qmaq_049, M_qmaq_04A, M_qmaq_04B, M_qmaq_04C, M_qmaq_04D, M_qmaq_04E, M_qmaq_04F, 
M_qmaq_050, M_qmaq_051, M_qmaq_052, M_qmaq_053, M_qmaq_054, M_qmaq_055, M_qmaq_056, M_qmaq_057, 
M_qmaq_058, M_qmaq_059, M_qmaq_05A, M_qmaq_05B, M_qmaq_05C, M_qmaq_05D, M_qmaq_05E, M_qmaq_05F, 
M_qmaq_060, M_qmaq_061, M_qmaq_062, M_qmaq_063, M_qmaq_064, M_qmaq_065, M_qmaq_066, M_qmaq_067, 
M_qmaq_068, M_qmaq_069, M_qmaq_06A, M_qmaq_06B, M_qmaq_06C, M_qmaq_06D, M_qmaq_06E, M_qmaq_06F, 
M_qmaq_070, M_qmaq_071, M_qmaq_072, M_qmaq_073, M_qmaq_074, M_qmaq_075, M_qmaq_076, M_qmaq_077, 
M_qmaq_078, M_qmaq_079, M_qmaq_07A, M_qmaq_07B, M_qmaq_07C, M_qmaq_07D, M_qmaq_07E, M_qmaq_07F, 
M_qmaq_080, M_qmaq_081, M_qmaq_082, M_qmaq_083, M_qmaq_084, M_qmaq_085, M_qmaq_086, M_qmaq_087, 
M_qmaq_088, M_qmaq_089, M_qmaq_08A, M_qmaq_08B, M_qmaq_08C, M_qmaq_08D, M_qmaq_08E, M_qmaq_08F, 
M_qmaq_090, M_qmaq_091, M_qmaq_092, M_qmaq_093, M_qmaq_094, M_qmaq_095, M_qmaq_096, M_qmaq_097, 
M_qmaq_098, M_qmaq_099, M_qmaq_09A, M_qmaq_09B, M_qmaq_09C, M_qmaq_09D, M_qmaq_09E, M_qmaq_09F, 
M_qmaq_0A0, M_qmaq_0A1, M_qmaq_0A2, M_qmaq_0A3, M_qmaq_0A4, M_qmaq_0A5, M_qmaq_0A6, M_qmaq_0A7, 
M_qmaq_0A8, M_qmaq_0A9, M_qmaq_0AA, M_qmaq_0AB, M_qmaq_0AC, M_qmaq_0AD, M_qmaq_0AE, M_qmaq_0AF, 
M_qmaq_0B0, M_qmaq_0B1, M_qmaq_0B2, M_qmaq_0B3, M_qmaq_0B4, M_qmaq_0B5, M_qmaq_0B6, M_qmaq_0B7, 
M_qmaq_0B8, M_qmaq_0B9, M_qmaq_0BA, M_qmaq_0BB, M_qmaq_0BC, M_qmaq_0BD, M_qmaq_0BE, M_qmaq_0BF, 
M_qmaq_0C0, M_qmaq_0C1, M_qmaq_0C2, M_qmaq_0C3, M_qmaq_0C4, M_qmaq_0C5, M_qmaq_0C6, M_qmaq_0C7, 
M_qmaq_0C8, M_qmaq_0C9, M_qmaq_0CA, M_qmaq_0CB, M_qmaq_0CC, M_qmaq_0CD, M_qmaq_0CE, M_qmaq_0CF, 
M_qmaq_0D0, M_qmaq_0D1, M_qmaq_0D2, M_qmaq_0D3, M_qmaq_0D4, M_qmaq_0D5, M_qmaq_0D6, M_qmaq_0D7, 
M_qmaq_0D8, M_qmaq_0D9, M_qmaq_0DA, M_qmaq_0DB, M_qmaq_0DC, M_qmaq_0DD, M_qmaq_0DE, M_qmaq_0DF, 
M_qmaq_0E0, M_qmaq_0E1, M_qmaq_0E2, M_qmaq_0E3, M_qmaq_0E4, M_qmaq_0E5, M_qmaq_0E6, M_qmaq_0E7, 
M_qmaq_0E8, M_qmaq_0E9, M_qmaq_0EA, M_qmaq_0EB, M_qmaq_0EC, M_qmaq_0ED, M_qmaq_0EE, M_qmaq_0EF, 
M_qmaq_0F0, M_qmaq_0F1, M_qmaq_0F2, M_qmaq_0F3, M_qmaq_0F4, M_qmaq_0F5, M_qmaq_0F6, M_qmaq_0F7, 
M_qmaq_0F8, M_qmaq_0F9, M_qmaq_0FA, M_qmaq_0FB, M_qmaq_0FC, M_qmaq_0FD, M_qmaq_0FE, M_qmaq_0FF, 
M_qmaq_100, M_qmaq_101, M_qmaq_102, M_qmaq_103, M_qmaq_104, M_qmaq_105, M_qmaq_106, M_qmaq_107, 
M_qmaq_108, M_qmaq_109, M_qmaq_10A, M_qmaq_10B, M_qmaq_10C, M_qmaq_10D, M_qmaq_10E, M_qmaq_10F, 
M_qmaq_110, M_qmaq_111, M_qmaq_112, M_qmaq_113, M_qmaq_114, M_qmaq_115, M_qmaq_116, M_qmaq_117, 
M_qmaq_118, M_qmaq_119, M_qmaq_11A, M_qmaq_11B, M_qmaq_11C, M_qmaq_11D, M_qmaq_11E, M_qmaq_11F, 
M_qmaq_120, M_qmaq_121, M_qmaq_122, M_qmaq_123, M_qmaq_124, M_qmaq_125, M_qmaq_126, M_qmaq_127, 
M_qmaq_128, M_qmaq_129, M_qmaq_12A, M_qmaq_12B, M_qmaq_12C, M_qmaq_12D, M_qmaq_12E, M_qmaq_12F, 
M_qmaq_130, M_qmaq_131, M_qmaq_132, M_qmaq_133, M_qmaq_134, M_qmaq_135, M_qmaq_136, M_qmaq_137, 
M_qmaq_138, M_qmaq_139, M_qmaq_13A, M_qmaq_13B, M_qmaq_13C, M_qmaq_13D, M_qmaq_13E, M_qmaq_13F, 
M_qmaq_140, M_qmaq_141, M_qmaq_142, M_qmaq_143, M_qmaq_144, M_qmaq_145, M_qmaq_146, M_qmaq_147, 
M_qmaq_148, M_qmaq_149, M_qmaq_14A, M_qmaq_14B, M_qmaq_14C, M_qmaq_14D, M_qmaq_14E, M_qmaq_14F, 
M_qmaq_150, M_qmaq_151, M_qmaq_152, M_qmaq_153, M_qmaq_154, M_qmaq_155, M_qmaq_156, M_qmaq_157, 
M_qmaq_158, M_qmaq_159, M_qmaq_15A, M_qmaq_15B, M_qmaq_15C, M_qmaq_15D, M_qmaq_15E, M_qmaq_15F, 
M_qmaq_160, M_qmaq_161, M_qmaq_162, M_qmaq_163, M_qmaq_164, M_qmaq_165, M_qmaq_166, M_qmaq_167, 
M_qmaq_168, M_qmaq_169, M_qmaq_16A, M_qmaq_16B, M_qmaq_16C, M_qmaq_16D, M_qmaq_16E, M_qmaq_16F, 
M_qmaq_170, M_qmaq_171, M_qmaq_172, M_qmaq_173, M_qmaq_174, M_qmaq_175, M_qmaq_176, M_qmaq_177, 
M_qmaq_178, M_qmaq_179, M_qmaq_17A, M_qmaq_17B, M_qmaq_17C, M_qmaq_17D, M_qmaq_17E, M_qmaq_17F, 
M_qmaq_180, M_qmaq_181, M_qmaq_182, M_qmaq_183, M_qmaq_184, M_qmaq_185, M_qmaq_186, M_qmaq_187, 
M_qmaq_188, M_qmaq_189, M_qmaq_18A, M_qmaq_18B, M_qmaq_18C, M_qmaq_18D, M_qmaq_18E, M_qmaq_18F, 
M_qmaq_190, M_qmaq_191, M_qmaq_192, M_qmaq_193, M_qmaq_194, M_qmaq_195, M_qmaq_196, M_qmaq_197, 
M_qmaq_198, M_qmaq_199, M_qmaq_19A, M_qmaq_19B, M_qmaq_19C, M_qmaq_19D, M_qmaq_19E, M_qmaq_19F, 
M_qmaq_1A0, M_qmaq_1A1, M_qmaq_1A2, M_qmaq_1A3, M_qmaq_1A4, M_qmaq_1A5, M_qmaq_1A6, M_qmaq_1A7, 
M_qmaq_1A8, M_qmaq_1A9, M_qmaq_1AA, M_qmaq_1AB, M_qmaq_1AC, M_qmaq_1AD, M_qmaq_1AE, M_qmaq_1AF, 
M_qmaq_1B0, M_qmaq_1B1, M_qmaq_1B2, M_qmaq_1B3, M_qmaq_1B4, M_qmaq_1B5, M_qmaq_1B6, M_qmaq_1B7, 
M_qmaq_1B8, M_qmaq_1B9, M_qmaq_1BA, M_qmaq_1BB, M_qmaq_1BC, M_qmaq_1BD, M_qmaq_1BE, M_qmaq_1BF, 
M_qmaq_1C0, M_qmaq_1C1, M_qmaq_1C2, M_qmaq_1C3, M_qmaq_1C4, M_qmaq_1C5, M_qmaq_1C6, M_qmaq_1C7, 
M_qmaq_1C8, M_qmaq_1C9, M_qmaq_1CA, M_qmaq_1CB, M_qmaq_1CC, M_qmaq_1CD, M_qmaq_1CE, M_qmaq_1CF, 
M_qmaq_1D0, M_qmaq_1D1, M_qmaq_1D2, M_qmaq_1D3, M_qmaq_1D4, M_qmaq_1D5, M_qmaq_1D6, M_qmaq_1D7, 
M_qmaq_1D8, M_qmaq_1D9, M_qmaq_1DA, M_qmaq_1DB, M_qmaq_1DC, M_qmaq_1DD, M_qmaq_1DE, M_qmaq_1DF, 
M_qmaq_1E0, M_qmaq_1E1, M_qmaq_1E2, M_qmaq_1E3, M_qmaq_1E4, M_qmaq_1E5, M_qmaq_1E6, M_qmaq_1E7, 
M_qmaq_1E8, M_qmaq_1E9, M_qmaq_1EA, M_qmaq_1EB, M_qmaq_1EC, M_qmaq_1ED, M_qmaq_1EE, M_qmaq_1EF, 
M_qmaq_1F0, M_qmaq_1F1, M_qmaq_1F2, M_qmaq_1F3, M_qmaq_1F4, M_qmaq_1F5, M_qmaq_1F6, M_qmaq_1F7, 
M_qmaq_1F8, M_qmaq_1F9, M_qmaq_1FA, M_qmaq_1FB, M_qmaq_1FC, M_qmaq_1FD, M_qmaq_1FE, M_qmaq_1FF, 
M_qmaq_200, };

byte qmas[1024+2];
byte qmar[1024+2];

void init_qmar( void ) {
  enum { shift=5, mask=(1<<shift)-1, sSCALE=1<<shift };
   uint p,p0;

   for( p0=0; p0<=SCALE; p0++ ) {
     p = p0>hSCALE ? SCALE-p0+hSCALE+1 : p0;

     uint p1 = p;
     uint lpb = ~(int(-(hSCALE+1)+p1)>>31);
     p1 = p1 - ((-SCALE+p1+p1)&lpb);
     p1 = (p1+mask)>>shift;
     p1 = qmaq[p1];

     uint p2 = (p+mask)>>shift;
//     uint p2 = (p+mask+(p>hSCALE))>>shift;
//     uint p2 = (int(p-hSCALE)/sSCALE) + (hSCALE>>shift);
//     qmar[p2] = p1+p1 + (lpb&1);
//     qmas[p2] = p1 + ((lpb&1)<<7);
//     qmas[p2] = (p1*2 + (lpb&1)) & 0x7F; // bit7=0
     qmas[p2] = (p1*2 + (lpb&1)) + ((lpb&1)<<7);
     qmar[p2] = (p1*2 + (lpb&1)) & 0x7F;
   }
//   qmar[0x200]=0xFE;
//   qmar[0x401]=0x01;
   qmas[0x401]=qmas[0x400];//0x80;
}



